robot_server:
  # host_ip: "192.168.2.187"
  # host_ip: "147.47.190.17"
  host_ip: "10.112.2.37"
  # host_ip: "127.0.0.1"
  # port: 8092
  port: 4243
  # left_robot_ip: "192.168.2.110"
  # left_robot_ip: "147.47.190.17"
  left_robot_ip: "10.0.0.2"
  right_robot_ip: "192.168.2.111"
publisher:
  vr_server_ip: &vr_server_ip '192.168.2.205'
  vr_server_port: 10002
  robot_publisher:
    robot_server_ip: ${task.robot_server.host_ip}
    robot_server_port: ${task.robot_server.port}
    fps: 120
    vr_server_ip: *vr_server_ip
    vr_server_tcp_port: 10001
    vr_server_force_port: 10005
teleop_server:
  # host_ip: "192.168.2.187"
  # port: 8082
  # host_ip: "10.112.2.37"
  host_ip: "127.0.0.1"
  port: 4245
  fps: 60
  use_force_control_for_gripper: False
  max_gripper_width: 0.05
  min_gripper_width: 0.0
  grasp_force: 7.0
  gripper_control_time_interval: 30  # 30 for Flexiv Gripper, 20 for PGC-50 gripper
  gripper_control_width_precision: 0.01  # 0.01 for PGC-50 gripper, 0.01 for Flexiv Grav Gripper
device_mapping_server:
  host_ip: '10.112.2.37'
  # host_ip: '127.0.0.1'
  # port: 8062
  port: 4244
transforms:
  calibration_path: 'data/calibration/v6'
logger:
  level: DEBUG